name: Testing secrets and variables

on: 
  workflow_dispatch:

jobs:
  run-on-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Testing secrets
        run: |
          echo "Your username is $USERNAME"
          echo "Your password is $PASSWORD"
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

      
   
