name: Testing secrets and variables

on: 
  workflow_dispatch:

jobs:
  run-on-ubuntu:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Testing secrets
        env:
          USERNAME: ${{ vars.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Your username is ${{env.USERNAME}}"
          echo "Your password is ${{env.PASSWORD}}"
          
        
    

      
   
