name: Testing secrets and variables

on:
  workflow_dispatch:

jobs:
  run-on-ubuntu:
    runs-on: ubuntu-latest

    # ðŸ”‘ THIS IS MANDATORY
    environment: dev

    steps:
      - name: Testing secrets
        env:
          USERNAME: ${{ vars.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
            
      
        run: |
         - uses: actions/check-out@v4
          python --version
          python construct.py
