name: Testing secrets and variables

on:
  workflow_dispatch:

jobs:
  run-on-ubuntu:
    runs-on: ubuntu-latest

    # ðŸ”‘ THIS IS MANDATORY
    environment: dev

    steps:
      - name: Testing secrets
        env:
          USERNAME: ${{ vars.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          echo "Your username is $USERNAME"
          echo "Your password is $PASSWORD"
